/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  pwrchainSidebar: [{ type: 'autogenerated', dirName: 'pwrchain' }],
  developersSidebar: [{ type: 'autogenerated', dirName: 'developers' }],
};

module.exports = sidebars;
